spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PETSHOPDB
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false